apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dotcms-db-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: local-path
  resources:
    requests:
      storage: {{ .Values.postgres.storage }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dotcms-os-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: local-path
  resources:
    requests:
      storage: {{ .Values.opensearch.storage }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dotcms-shared-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: local-path
  resources:
    requests:
      storage: {{ .Values.dotcms.storage }}
