apiVersion: v1
kind: Secret
metadata:
  name: dotcms-db-secret
  namespace: {{ .Values.namespace }}
  labels:
    app: dotcms
type: Opaque
stringData:
  POSTGRES_DB: {{ .Values.postgres.db }}
  POSTGRES_USER: {{ .Values.postgres.user }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password }}
  DOT_INITIAL_ADMIN_PASSWORD: {{ .Values.dotcms.adminPassword }}
